import sys

def compute(mod, base,power):
    if base == 1:
        return base
    else:
        return ((base**power)%mod)
print(" Enter a prime number:",end="")
p = int(input())
print(" Enter primitive root of above prime:",end="")
q = int(input())
print(" Enter A's private key:",end="")
a = int(input())
Ya = compute(p,q,a)

print(" Enter B's private key:",end="")
b = int(input())
Yb = compute(p,q,b)
print(" A's public key is:",end="")
print(Ya)
print(" B's public key is:",end="")
print(Yb)
print(" Secret key as generated by A is:",end="")
print(compute(p,Yb,a))
print(" Secret key as generated by B is:",end="")
print(compute(p,Ya,b))

